name: Validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  shell:
    name: Shell validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Validate scripts
        run: make test
